name: Release

on:
- release
#  release:
#    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
    - name: Build pre-requisites
      run: |
        make ${MAKEOPTS} -C mpy-cross
        make ${MAKEOPTS} -C ports/unix submodules
        make ${MAKEOPTS} -C ports/unix deplibs
    - name: Build Unix port
      run: |
        make ${MAKEOPTS} -C ports/unix
    - name: Upload release files
      uses: pfalcon/github-action-publish-binaries@master
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
          args: "ports/unix/pycopy"
